spring.application.name=bioclick

spring.profiles.active=prod, pgsql
spring.docker.compose.enabled=true
spring.docker.compose.file=../../docker-compose.yml
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show_sql=true

spring.jpa.open-in-view=false

jwt.secret=mi_clave_secreta_segura_es_la_mas_segura
jwt.duration=120
jwt.refresh.duration=120

sendgrid.api.key=${SG_API_KEY}

storage.location=./uploads

# Max attachment size
spring.servlet.multipart.max-file-size=5MB
# Max request size
spring.servlet.multipart.max-request-size=10MB



